name = "iitm-bs-chatbot"
main = "worker.js"
compatibility_date = "2025-07-28"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

[assets]
directory = "./static"
binding = "ASSETS"
